spring.application.name=labour-wage-system
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/labour_wage_db
spring.datasource.username=labour_admin
spring.datasource.password=labour123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JWT
jwt.secret=labour-wage-system-super-secret-key-2024-make-it-long
jwt.expiration=86400000

# HMAC QR Secret
qr.secret.key=qr-hmac-secret-key-labour-2024

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
file.upload.dir=uploads/
```

---

## Step 10 — Create the folder structure

In IntelliJ, right-click on `src/main/java/com/labourwage/labourwagesystem` and create these packages one by one (right-click → New → Package):

com.labourwage.labourwagesystem.config
com.labourwage.labourwagesystem.controller
com.labourwage.labourwagesystem.service
com.labourwage.labourwagesystem.repository
com.labourwage.labourwagesystem.entity
com.labourwage.labourwagesystem.dto.request
com.labourwage.labourwagesystem.dto.response
com.labourwage.labourwagesystem.enums
com.labourwage.labourwagesystem.exception
com.labourwage.labourwagesystem.security
com.labourwage.labourwagesystem.util


Also create this folder under `src/main/resources`:

db/migration
